### ISSUE TITLE
Q2 問題

### ISSUE THREAD

**Issue by gordon636798** [wst24365888/get_number_of_entering_a_wait_queue#1]
為什麼進入 wait_queue 的次數比 context switch 多好多?

裡面的 IO 應該也才 10 幾次，為什麼會進入 wait_queue 2000 多次

**Comment by kevinjone25** [comment]
@gordon636798 我是其中一個contributor 2000次的結果是因為我們當初沒有想到要在copy_thread()的地方做，一直在wake_up_function附近trace，所以我們最初在實驗時是在ttwu_do_wake_up()和try_to_wake_up()兩個地方分別將task_struct裡的counter去做遞增的動作，但是兩次的結果都是在2000多次並且會持續遞增下去，所以我們在懷疑task_struct在各個thread並沒有自動被清0，並被其他的process去重複利用，但是我們找不到一個把task_struct initialize的地方，所以才導致了2000多次並持續遞增的情況。其後校正回歸加回copy_thread()以後，次數已回歸正常，感謝您的觀看和提醒!!
