### ISSUE TITLE
初始化task_struct的位置

### ISSUE THREAD

**Issue by X-Engineer-001** [wst24365888/get_number_of_entering_a_wait_queue#3]
不好意思，關於README中「原本以為是要在狀態圖中的fork清除task_struct的狀態，但是搞錯了方向，要在copy_thread的時候才把task_struct()清0」，想請問「在狀態圖中的fork清除task_struct的狀態」是甚麼意思？
你們曾經嘗試在哪些地方初始化而沒得到正常結果呢？

**Comment by wst24365888** [comment]
Hi，您好，題意是要把process進入wait_queue的次數算出來，我們最終的想法是在`task_struct`加一個`enter_queue_count`的欄位，並在每次`copy_thread`之後重置計數器並做運算。

![](https://i.imgur.com/El3QwBd.png)

我們參考這張圖，原本以為是在狀態圖中的`fork`，kernel會幫我們重置`task_struct`的counter，但是其實是我們搞錯了方向，當初想驗證，但在`fork`附近也找不到一個能取得`task_struct`的方法（當然，因為我們當初的疏忽，也trace的不夠深），所以只在`ttwu_wake_up`中寫了將counter遞增的段落。

但後來實驗結果顯示`enter_queue_count`大約在2000筆上下，而且每次是遞增的，因此我們推論在每次user space test code開始時，其實是把上一個`task_struct`進行複製，然後再把counter繼續往上加。後來trace到`copy_thread`相關的部分，也證明我們原本的想法是錯的，必須要在`copy_thread`的時候把`task_struct`裡的counter清0，這樣才可以準確印出實際`enter_wiat_queue`的次數。
